import React from 'react';
import { View, Text, StyleSheet, SafeAreaView, Pressable } from 'react-native';
import { router } from 'expo-router';

export default function HomeScreen() {
  return (
      <SafeAreaView style={styles.container}>
            <View style={styles.content}>
                    <Text style={styles.title}>MARVELVAULT</Text>

                            <Text style={styles.subtitle}>
                                      YOUR MARVEL UNIVERSE
                                              </Text>

                                                      <View style={styles.heroCard}>
                                                                <Text style={styles.heroTitle}>MARVEL</Text>

                                                                          <Text style={styles.heroText}>
                                                                                      Explore movies, series and watch orders.
                                                                                                </Text>
                                                                                                        </View>

                                                                                                                <Pressable
                                                                                                                          style={styles.button}
                                                                                                                                    onPress={() => router.push('/movies')}
                                                                                                                                            >
                                                                                                                                                      <Text style={styles.buttonText}>MOVIES</Text>
                                                                                                                                                              </Pressable>

                                                                                                                                                                      <Pressable
                                                                                                                                                                                style={styles.button}
                                                                                                                                                                                          onPress={() => router.push('/series')}
                                                                                                                                                                                                  >
                                                                                                                                                                                                            <Text style={styles.buttonText}>SERIES</Text>
                                                                                                                                                                                                                    </Pressable>

                                                                                                                                                                                                                            <Pressable
                                                                                                                                                                                                                                      style={styles.button}
                                                                                                                                                                                                                                                onPress={() => router.push('/watch-order')}
                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                  <Text style={styles.buttonText}>WATCH ORDER</Text>
                                                                                                                                                                                                                                                                          </Pressable>

                                                                                                                                                                                                                                                                                  <Pressable
                                                                                                                                                                                                                                                                                            style={styles.button}
                                                                                                                                                                                                                                                                                                      onPress={() => router.push('/settings')}
                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                        <Text style={styles.buttonText}>SETTINGS</Text>
                                                                                                                                                                                                                                                                                                                                </Pressable>

                                                                                                                                                                                                                                                                                                                                        <Text style={styles.footer}>
                                                                                                                                                                                                                                                                                                                                                  Version 1.0.0
                                                                                                                                                                                                                                                                                                                                                          </Text>
                                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                                    </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                      const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                        container: {
                                                                                                                                                                                                                                                                                                                                                                            flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: '#080808',
                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                    content: {
                                                                                                                                                                                                                                                                                                                                                                                        flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                            padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                    title: {
                                                                                                                                                                                                                                                                                                                                                                                                        color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                    letterSpacing: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                        textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                            subtitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#666666',
                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                        letterSpacing: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                        heroCard: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: '#151515',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 24,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderColor: '#292929',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    heroTitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 25,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    letterSpacing: 3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        heroText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: '#777777',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        lineHeight: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            button: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: '#121212',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderColor: '#222222',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                paddingVertical: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            buttonText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            letterSpacing: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                footer: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#444444',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })