import React, { useState } from 'react';
import {
  SafeAreaView,
    View,
      Text,
        StyleSheet,
          ScrollView,
          } from 'react-native';
          import { router } from 'expo-router';

          import movies from '../data/movies';
          import MovieCard from '../components/movie-card';
          import SearchBar from '../components/search-bar';
          import EmptyState from '../components/empty-state';
          import SectionTitle from '../components/section-title';

          export default function MoviesScreen() {
            const [search, setSearch] = useState('');

              const filteredMovies = movies.filter((movie) =>
                  movie.title.toLowerCase().includes(search.toLowerCase())
                    );

                      return (
                          <SafeAreaView style={styles.container}>
                                <ScrollView
                                        contentContainerStyle={styles.content}
                                                showsVerticalScrollIndicator={false}
                                                      >
                                                              <Text style={styles.heading}>MOVIES</Text>

                                                                      <Text style={styles.subtitle}>
                                                                                MARVEL MOVIE COLLECTION
                                                                                        </Text>

                                                                                                <SearchBar
                                                                                                          value={search}
                                                                                                                    onChangeText={setSearch}
                                                                                                                              placeholder="Search movies..."
                                                                                                                                      />

                                                                                                                                              <SectionTitle
                                                                                                                                                        title="MOVIE LIBRARY"
                                                                                                                                                                  subtitle={`${filteredMovies.length} TITLES`}
                                                                                                                                                                          />

                                                                                                                                                                                  {filteredMovies.length > 0 ? (
                                                                                                                                                                                            filteredMovies.map((movie) => (
                                                                                                                                                                                                        <MovieCard
                                                                                                                                                                                                                      key={movie.id}
                                                                                                                                                                                                                                    movie={movie}
                                                                                                                                                                                                                                                  onPress={() =>
                                                                                                                                                                                                                                                                  router.push({
                                                                                                                                                                                                                                                                                    pathname: '/movie-details',
                                                                                                                                                                                                                                                                                                      params: { id: movie.id },
                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                            <EmptyState
                                                                                                                                                                                                                                                                                                                                                                                        title="NO MOVIES FOUND"
                                                                                                                                                                                                                                                                                                                                                                                                    message="Try a different movie title."
                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                            </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                                </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                  const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                    container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                        flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: '#080808',
                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                content: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        paddingBottom: 50,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                            heading: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            letterSpacing: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    subtitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#666666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                letterSpacing: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: 25,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })