import React, { useState } from 'react';
import {
  SafeAreaView,
    View,
      Text,
        StyleSheet,
          ScrollView,
          } from 'react-native';
          import { router } from 'expo-router';

          import series from '../data/series';
          import SeriesCard from '../components/series-card';
          import SearchBar from '../components/search-bar';
          import EmptyState from '../components/empty-state';
          import SectionTitle from '../components/section-title';

          export default function SeriesScreen() {
            const [search, setSearch] = useState('');

              const filteredSeries = series.filter((item) =>
                  item.title.toLowerCase().includes(search.toLowerCase())
                    );

                      return (
                          <SafeAreaView style={styles.container}>
                                <ScrollView
                                        contentContainerStyle={styles.content}
                                                showsVerticalScrollIndicator={false}
                                                      >
                                                              <Text style={styles.heading}>SERIES</Text>

                                                                      <Text style={styles.subtitle}>
                                                                                MARVEL SERIES COLLECTION
                                                                                        </Text>

                                                                                                <SearchBar
                                                                                                          value={search}
                                                                                                                    onChangeText={setSearch}
                                                                                                                              placeholder="Search series..."
                                                                                                                                      />

                                                                                                                                              <SectionTitle
                                                                                                                                                        title="SERIES LIBRARY"
                                                                                                                                                                  subtitle={`${filteredSeries.length} TITLES`}
                                                                                                                                                                          />

                                                                                                                                                                                  {filteredSeries.length > 0 ? (
                                                                                                                                                                                            filteredSeries.map((item) => (
                                                                                                                                                                                                        <SeriesCard
                                                                                                                                                                                                                      key={item.id}
                                                                                                                                                                                                                                    series={item}
                                                                                                                                                                                                                                                  onPress={() =>
                                                                                                                                                                                                                                                                  router.push({
                                                                                                                                                                                                                                                                                    pathname: '/series-details',
                                                                                                                                                                                                                                                                                                      params: { id: item.id },
                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                            <EmptyState
                                                                                                                                                                                                                                                                                                                                                                                        title="NO SERIES FOUND"
                                                                                                                                                                                                                                                                                                                                                                                                    message="Try a different series title."
                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                            </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                                </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                  const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                    container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                        flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: '#080808',
                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                content: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        paddingBottom: 50,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                            heading: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            letterSpacing: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    subtitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#666666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                letterSpacing: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: 25,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })