import React from 'react';
import {
  View,
    Text,
      StyleSheet,
        SafeAreaView,
          ScrollView,
            Pressable,
            } from 'react-native';

            export default function SeriesDetailsScreen() {
              return (
                  <SafeAreaView style={styles.container}>
                        <ScrollView
                                contentContainerStyle={styles.content}
                                        showsVerticalScrollIndicator={false}
                                              >
                                                      <View style={styles.poster}>
                                                                <Text style={styles.posterText}>LOKI</Text>
                                                                          <Text style={styles.posterSubtext}>2021</Text>
                                                                                  </View>

                                                                                          <Text style={styles.title}>Loki</Text>

                                                                                                  <Text style={styles.meta}>
                                                                                                            2021  •  MCU  •  2 SEASONS
                                                                                                                    </Text>

                                                                                                                            <View style={styles.divider} />

                                                                                                                                    <Text style={styles.sectionTitle}>OVERVIEW</Text>

                                                                                                                                            <Text style={styles.description}>
                                                                                                                                                      The mercurial villain Loki resumes his role as the God of
                                                                                                                                                                Mischief in a story that takes place after the events of
                                                                                                                                                                          Avengers: Endgame.
                                                                                                                                                                                  </Text>

                                                                                                                                                                                          <Text style={styles.sectionTitle}>UNIVERSE</Text>

                                                                                                                                                                                                  <View style={styles.infoCard}>
                                                                                                                                                                                                            <Text style={styles.infoLabel}>MARVEL CINEMATIC UNIVERSE</Text>
                                                                                                                                                                                                                      <Text style={styles.infoValue}>MCU</Text>
                                                                                                                                                                                                                              </View>

                                                                                                                                                                                                                                      <Text style={styles.sectionTitle}>SEASONS</Text>

                                                                                                                                                                                                                                              <View style={styles.seasonCard}>
                                                                                                                                                                                                                                                        <Text style={styles.seasonTitle}>SEASON 1</Text>
                                                                                                                                                                                                                                                                  <Text style={styles.seasonText}>6 Episodes</Text>
                                                                                                                                                                                                                                                                          </View>

                                                                                                                                                                                                                                                                                  <View style={styles.seasonCard}>
                                                                                                                                                                                                                                                                                            <Text style={styles.seasonTitle}>SEASON 2</Text>
                                                                                                                                                                                                                                                                                                      <Text style={styles.seasonText}>6 Episodes</Text>
                                                                                                                                                                                                                                                                                                              </View>

                                                                                                                                                                                                                                                                                                                      <Pressable style={styles.watchButton}>
                                                                                                                                                                                                                                                                                                                                <Text style={styles.watchButtonText}>
                                                                                                                                                                                                                                                                                                                                            ✓ MARK AS WATCHED
                                                                                                                                                                                                                                                                                                                                                      </Text>
                                                                                                                                                                                                                                                                                                                                                              </Pressable>

                                                                                                                                                                                                                                                                                                                                                                      <Pressable style={styles.linkButton}>
                                                                                                                                                                                                                                                                                                                                                                                <Text style={styles.linkButtonText}>
                                                                                                                                                                                                                                                                                                                                                                                            OFFICIAL WATCH OPTIONS
                                                                                                                                                                                                                                                                                                                                                                                                      </Text>
                                                                                                                                                                                                                                                                                                                                                                                                              </Pressable>
                                                                                                                                                                                                                                                                                                                                                                                                                    </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                        </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                          const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                            container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: '#080808',
                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                        content: {
                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                paddingBottom: 40,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                    poster: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        height: 300,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: '#181818',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderColor: '#292929',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: 24,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        posterText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 42,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        letterSpacing: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            posterSubtext: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#777777',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            letterSpacing: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                meta: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#777777',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                letterSpacing: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    divider: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        height: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: '#222222',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginVertical: 24,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sectionTitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '800',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    letterSpacing: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#999999',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lineHeight: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                infoCard: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    backgroundColor: '#121212',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderColor: '#222222',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        infoLabel: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: '#666666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    letterSpacing: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        infoValue: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: '800',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            seasonCard: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: '#121212',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderColor: '#222222',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        seasonTitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: '800',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        seasonText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: '#666666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 11,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        watchButton: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 13,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    paddingVertical: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    watchButtonText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#000000',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    letterSpacing: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        linkButton: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: '#151515',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 13,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    paddingVertical: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderColor: '#292929',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    linkButtonText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '800',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    letterSpacing: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });