import React from 'react';
import {
  SafeAreaView,
    ScrollView,
      View,
        Text,
          StyleSheet,
          } from 'react-native';

          import EmptyState from '../components/empty-state';

          export default function WatchlistScreen() {
            const watchlist = [];

              return (
                  <SafeAreaView style={styles.container}>
                        <ScrollView
                                contentContainerStyle={styles.content}
                                        showsVerticalScrollIndicator={false}
                                              >
                                                      <Text style={styles.heading}>MY LIST</Text>

                                                              <Text style={styles.subtitle}>
                                                                        YOUR SAVED MARVEL TITLES
                                                                                </Text>

                                                                                        <View style={styles.infoCard}>
                                                                                                  <Text style={styles.infoTitle}>
                                                                                                              WATCHLIST
                                                                                                                        </Text>

                                                                                                                                  <Text style={styles.infoText}>
                                                                                                                                              Movies and series you want to watch will appear
                                                                                                                                                          here.
                                                                                                                                                                    </Text>
                                                                                                                                                                            </View>

                                                                                                                                                                                    {watchlist.length === 0 ? (
                                                                                                                                                                                              <EmptyState
                                                                                                                                                                                                          title="YOUR LIST IS EMPTY"
                                                                                                                                                                                                                      message="Add movies or series to your watchlist and they will appear here."
                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                  watchlist.map((item) => (
                                                                                                                                                                                                                                                              <View key={item.id} style={styles.item}>
                                                                                                                                                                                                                                                                            <Text style={styles.itemTitle}>
                                                                                                                                                                                                                                                                                            {item.title}
                                                                                                                                                                                                                                                                                                          </Text>

                                                                                                                                                                                                                                                                                                                        <Text style={styles.itemMeta}>
                                                                                                                                                                                                                                                                                                                                        {item.type}
                                                                                                                                                                                                                                                                                                                                                      </Text>
                                                                                                                                                                                                                                                                                                                                                                  </View>
                                                                                                                                                                                                                                                                                                                                                                            ))
                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                          </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                              </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                  container: {
                                                                                                                                                                                                                                                                                                                                                                                                      flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                          backgroundColor: '#080808',
                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                              content: {
                                                                                                                                                                                                                                                                                                                                                                                                                  padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                      paddingBottom: 50,
                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                          heading: {
                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                          letterSpacing: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                              marginTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                },

                                                                                                                                                                                                                                                                                                                                                                                                                                                  subtitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: '#666666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              letterSpacing: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginBottom: 25,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          infoCard: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: '#151515',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderColor: '#292929',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      infoTitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      letterSpacing: 1.2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          infoText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#777777',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 11,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      lineHeight: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginTop: 7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              item: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: '#121212',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderColor: '#222222',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginBottom: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          itemTitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: '800',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          itemMeta: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: '#666666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginTop: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });