import React from 'react';
import {
  View,
    Text,
      StyleSheet,
        SafeAreaView,
          ScrollView,
          } from 'react-native';

          const watchOrder = [
            {
                number: 1,
                    title: 'Iron Man',
                        year: '2008',
                          },
                            {
                                number: 2,
                                    title: 'The Incredible Hulk',
                                        year: '2008',
                                          },
                                            {
                                                number: 3,
                                                    title: 'Iron Man 2',
                                                        year: '2010',
                                                          },
                                                            {
                                                                number: 4,
                                                                    title: 'Thor',
                                                                        year: '2011',
                                                                          },
                                                                            {
                                                                                number: 5,
                                                                                    title: 'Captain America: The First Avenger',
                                                                                        year: '2011',
                                                                                          },
                                                                                            {
                                                                                                number: 6,
                                                                                                    title: 'The Avengers',
                                                                                                        year: '2012',
                                                                                                          },
                                                                                                          ];

                                                                                                          export default function WatchOrderScreen() {
                                                                                                            return (
                                                                                                                <SafeAreaView style={styles.container}>
                                                                                                                      <ScrollView
                                                                                                                              contentContainerStyle={styles.content}
                                                                                                                                      showsVerticalScrollIndicator={false}
                                                                                                                                            >
                                                                                                                                                    <Text style={styles.heading}>WATCH ORDER</Text>

                                                                                                                                                            <Text style={styles.subtitle}>
                                                                                                                                                                      MARVEL CINEMATIC UNIVERSE
                                                                                                                                                                              </Text>

                                                                                                                                                                                      <View style={styles.modeCard}>
                                                                                                                                                                                                <Text style={styles.modeTitle}>
                                                                                                                                                                                                            RELEASE ORDER
                                                                                                                                                                                                                      </Text>

                                                                                                                                                                                                                                <Text style={styles.modeText}>
                                                                                                                                                                                                                                            Follow the Marvel story in its original release order.
                                                                                                                                                                                                                                                      </Text>
                                                                                                                                                                                                                                                              </View>

                                                                                                                                                                                                                                                                      {watchOrder.map((item) => (
                                                                                                                                                                                                                                                                                <View key={item.number} style={styles.item}>
                                                                                                                                                                                                                                                                                            <View style={styles.numberCircle}>
                                                                                                                                                                                                                                                                                                          <Text style={styles.number}>
                                                                                                                                                                                                                                                                                                                          {item.number}
                                                                                                                                                                                                                                                                                                                                        </Text>
                                                                                                                                                                                                                                                                                                                                                    </View>

                                                                                                                                                                                                                                                                                                                                                                <View style={styles.line} />

                                                                                                                                                                                                                                                                                                                                                                            <View style={styles.info}>
                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.title}>
                                                                                                                                                                                                                                                                                                                                                                                                          {item.title}
                                                                                                                                                                                                                                                                                                                                                                                                                        </Text>

                                                                                                                                                                                                                                                                                                                                                                                                                                      <Text style={styles.year}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.year}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Text style={styles.note}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    More movies and series will be added to the complete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              MarvelVault watch order.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ScrollView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: '#080808',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                content: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        paddingBottom: 50,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            heading: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 30,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            letterSpacing: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    subtitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#666666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 11,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                letterSpacing: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: 25,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modeCard: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: '#151515',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: 25,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderColor: '#292929',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        modeTitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        letterSpacing: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modeText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#777777',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        lineHeight: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                item: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flexDirection: 'row',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            minHeight: 72,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                numberCircle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: 42,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        height: 42,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: 21,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: '#181818',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderColor: '#333333',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    number: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 13,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    line: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: 25,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            height: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: '#292929',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginHorizontal: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        info: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: '#121212',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 13,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: 13,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderWidth: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderColor: '#222222',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '800',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    year: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#666666',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 11,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    note: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#555555',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 11,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                lineHeight: 17,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: 25,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });